### ISSUE TITLE
crash on trie_remove

### ISSUE THREAD

**Issue by dselivanov** [Ironholds/triebeard#6] opened 2016-07-11 13:13 UTC
```r
library(triebeard)
trie2 = trie(as.character(1:1e6), 1:1e6)
trie_remove(trie2, as.character(1:1e6) )

 *** caught segfault ***
address 0x2c, cause 'memory not mapped'

Traceback:
 1: .Call("triebeard_remove_trie_integer", PACKAGE = "triebeard",     trie, keys)
 2: remove_trie_integer(trie, keys)
 3: trie_remove.integer_trie(trie2, as.character(1:1e+06))
 4: trie_remove(trie2, as.character(1:1e+06))
```

```r
sessionInfo()
```

> R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.5 (Yosemite)
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

**Comment by Ironholds** [comment] 2016-07-11 15:18
Takes a bloody long time (is this a real use case or deliberate stress-testing?) but the crash happens at my end as well. I'm actually about to go on holiday so I'm unlikely to be able to get to this this week - @wrathematics any chance you'd be able to take a look? (Totally fine if not).

**Comment by dselivanov** [comment] 2016-07-11 15:21
okay, with 10 instead of 1e6 it also crash R :-)

**Comment by wrathematics** [comment] 2016-07-11 15:37
First check from valgrind:

```
==4959== More than 10000000 total errors detected.  I'm not reporting any more.
```

lol what did you do!?

As best as I can tell, the error happens when you remove the last entry from a trie of any size (this is also unusally slow?). I'll look into it.

**Comment by Ironholds** [comment] 2016-07-11 15:42
...Doh. How on earth did I not write a unit test for "completely emptying a trie". Bad Oliver.

**Comment by wrathematics** [comment] 2016-07-11 15:54
I think the problem is your size calculation. It's dereferencing a `NULL` or computing on garbage or something; it's really hard to tell.  I thought `radix.begin()` returned a pointer, but apparently not, since the compiler errors when I try to check it against `NULL`. Regardless if I manually set the size to 0, no crash.

This is one of the reasons I hate the STL and all monstrosities like it, fwiw.

**Comment by wrathematics** [comment] 2016-07-11 15:59
There's a `size()` method in the `radix_tree` class. Is there a reason not to use that?

Using that, I get the following:

```r
library(triebeard)
trie2 = trie(as.character(1:2), 1:2)
trie_remove(trie2, as.character(1) )
trie2
## A integer_trie object with 1 entries
trie_remove(trie2, as.character(2) )
trie2
## A integer_trie object with 0 entries
```

**Comment by Ironholds** [comment] 2016-07-11 16:09
None whatsoever; the existing size method is a legacy of a weird pointer dereferencing issue in version 0.0.0.0.0.1 that left the internal size method inaccessible.

**Comment by Ironholds** [comment] 2016-07-11 16:48
Should now be fixed on the development branch!

**Closed by Ironholds** 2016-07-11 16:48 UTC
